change format of .cloginrc method variable.  now multivalued from the set 	(ssh | telnet | rsh)

diff --git a/bin/clogin.in b/bin/clogin.in
--- a/bin/clogin.in
+++ b/bin/clogin.in
@@ -252,39 +252,56 @@ proc source_password_file { } {
 }
 
 # Log into the router.
-proc login { router user userpswd passwd enapasswd prompt cyphertype } {
+proc login { router user userpswd passwd enapasswd prompt cmethod cyphertype } {
     global spawn_id in_proc do_command do_script
     global u_prompt p_prompt e_prompt
     set in_proc 1
-    set tryssh 1
 
-    # Telnet to the router & try to login.
-    if [ catch {spawn telnet $router} reason ] {
-	send_user "Error: failed to telnet: $reason\n"
-	exit 1
-    }
-    sleep 0.3
-
-    # This helps cleanup each expect clause.
-    expect_after {
-	timeout {
-	    send_user "\nError: TIMEOUT reached\n"
-	    catch {close}; wait
-	    if { $in_proc} {
-		return 1
-	    } else {
-		continue
+    # try each of the connection methods in $cmethod until one is successful
+    set progs [llength $cmethod]
+    foreach prog [lrange $cmethod 0 end] {
+	if ![string compare $prog "telnet"] {
+	    if [ catch {spawn telnet $router} reason ] {
+		send_user "Error: telnet failed: $reason\n"
+		exit 1
 	    }
-	} eof {
-	    send_user "\nError: EOF received\n"
-	    catch {close}; wait
-	    if { $in_proc} {
-		return 1
-	    } else {
-		continue
+	} elseif ![string compare $prog "ssh"] {
+	    if [ catch {spawn ssh -c $cyphertype -x -l $user $router} reason ] {
+		send_user "Error: ssh failed: $reason\n"
+		exit 1
+	    }
+	} elseif ![string compare $prog "rsh"] {
+	    if [ catch {spawn rsh -l $user $router} reason ] {
+		send_user "Error: rsh failed: $reason\n"
+		exit 1
+	    }
+	} else {
+	    puts "ERROR: unknown connection method: $prog"
+	    return 1
+	}
+	incr progs -1
+	sleep 0.3
+
+	# This helps cleanup each expect clause.
+	expect_after {
+	    timeout {
+		send_user "\nError: TIMEOUT reached\n"
+		catch {close}; wait
+		if { $in_proc} {
+		    return 1
+		} else {
+		    continue
+		}
+	    } eof {
+		send_user "\nError: EOF received\n"
+		catch {close}; wait
+		if { $in_proc} {
+		    return 1
+		} else {
+		    continue
+		}
 	    }
 	}
-    }
 
     # Here we get a little tricky.  There are several possibilities:
     # the router can ask for a username and passwd and then
@@ -294,19 +311,10 @@ proc login { router user userpswd passwd enapasswd prompt cyphertype } {
     # then it will just send the passwd.
     # if telnet fails with connection refused, try ssh
     expect {
-	"Connection refused" {
-	    close; wait
-	    if { $tryssh } {
-	    if [ catch {spawn ssh -c $cyphertype -x -l $user $router} reason ] {
-		send_user "Error: failed to ssh: $reason\n"
-		exit 1
-	    }
-	    set tryssh 0
-	    sleep 0.3
-	    exp_continue
-	    } else {
-		expect eof
-		send_user "Error: Connection Refused\n"; wait; return 1
+	-re "(Connection refused|Secure connection \[^\n\r]+ refused|Connection closed by)" {
+	    catch {close}; wait
+	    if !$progs {
+		send_user "\nError: Connection Refused ($prog)\n"; return 1
 	    }
 	} eof { send_user "Error: Couldn't login\n"; wait; return 1
 	} "Unknown host\r\n" {
@@ -330,12 +338,18 @@ proc login { router user userpswd passwd enapasswd prompt cyphertype } {
 	-re "$u_prompt"	{ send "$user\r"
 	    expect {
 		eof			{ send_user "Error: Couldn't login\n"; wait; return 1 }
+		"Login invalid"		{ send_user "Error: Invalid login\n"; vatch {close}; wait; return 1 }
 		-re "$p_prompt"		{ send "$userpswd\r" }
 		"$prompt"		{ set in_proc 0; return 0 }
 	    }
 	    exp_continue
 	}
-	-re "$p_prompt"	{ send "$passwd\r"
+	-re "$p_prompt"	{
+	    if ![string compare $prog "ssh"] {
+		send "$userpswd\r"
+	    } else {
+		send "$passwd\r"
+	    }
 	    expect {
 		eof		{ send_user "Error: Couldn't login\n"; wait; return 1 }
 		-re "$e_prompt"	{ send "$enapasswd\r" }
@@ -343,7 +357,7 @@ proc login { router user userpswd passwd enapasswd prompt cyphertype } {
 	    }
 	    exp_continue
 	}
-	"$prompt"	{ }
+	"$prompt"	{ break; }
 	denied		{ send_user "Error: Check your passwd for $router\n"
 			    if { $do_command || $do_script } {
 			      send "exit\r"
@@ -355,6 +369,7 @@ proc login { router user userpswd passwd enapasswd prompt cyphertype } {
 			}
 	"% Bad passwords" {send_user "Error: Check your passwd for $router\n"; return 1 }
     }
+}
     set in_proc 0
     return 0
 }
@@ -404,8 +419,8 @@ proc run_commands { prompt command } {
 	set commands [split $command \;]
 	set num_commands [llength $commands]
 
-	# the pager can not be turned off per-session on the PIX, so we have
-	# to look for the "More" prompt
+	# the pager can not be turned off on the PIX, so we have to look
+	# for the "More" prompt
 	for {set i 0} {$i < $num_commands} { incr i} {
 	    send "[subst -nocommands [lindex $commands $i]]\r"
 	    expect {
@@ -527,8 +542,12 @@ foreach router [lrange $argv $i end] {
       if { "$cyphertype" == "" } { set cyphertype "3des" }
     }
 
+    # Figure out connection method
+    set cmethod [find method $router]
+    if { "$cmethod" == "" } { set cmethod {{telnet} {ssh}} }
+
     # Login to the router
-    if {[login $router $ruser $userpswd $passwd $enapasswd $prompt $cyphertype]} {
+    if {[login $router $ruser $userpswd $passwd $enapasswd $prompt $cmethod $cyphertype]} {
 	continue
     }
     if { $enable } {
