use mv -f to rename temp files and check exit code. helps deal with dest file that not owned by rancid.

diff --git a/bin/control_rancid.in b/bin/control_rancid.in
--- a/bin/control_rancid.in
+++ b/bin/control_rancid.in
@@ -1,7 +1,6 @@
 #!/bin/sh
 ##
-##
-## Copyright (C) 1996-2001 by Henry Kilmer.
+## Copyright (C) 1996-2003 by Henry Kilmer, Andrew Partan, and John Heasley.
 ## All rights reserved.
 ##
 ## This software may be freely copied, modified and redistributed without
@@ -236,9 +235,17 @@ then
     cd $DIR
 
 fi
-mv routers.all.new routers.all
-mv routers.down.new routers.down
-mv routers.up.new routers.up
+if [ $? -eq 0 ]; then
+    echo "Error: could not rename routers.all.new"
+fi
+mv -f routers.down.new routers.down
+if [ $? -eq 0 ]; then
+    echo "Error: could not rename routers.down.new"
+fi
+mv -f routers.up.new routers.up
+if [ $? -eq 0 ]; then
+    echo "Error: could not rename routers.up.new"
+fi
 rm -f routers.db
 trap 'rm -fr $TMP;' 1 2 15
 
