- use sysconfdir to find rancid.conf - use new LOGDIR var from rancid.conf - fail gracefully if we can not create the logs dir - WS nits

diff --git a/bin/rancid-run.in b/bin/rancid-run.in
--- a/bin/rancid-run.in
+++ b/bin/rancid-run.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! /bin/sh
 ##
 ## $Id$
 ##
@@ -16,11 +16,11 @@
 ## or its effect upon hardware, computer systems, other software, or
 ## anything else.
 ##
-# do diffs for each of the diff groups ($LIST_OF_GROUPS) from
-# <BASEDIR>/etc/rancid.conf
+# Run rancid for each of the groups defined by $LIST_OF_GROUPS in
+# @sysconfdir@/rancid.conf or specified on the command-line.
 ##
 
-ENVFILE="`dirname $0`/../etc/rancid.conf"
+ENVFILE="@sysconfdir@/rancid.conf"
 
 . $ENVFILE
 
@@ -74,12 +74,12 @@ fi
 if [ $# -ge 1 ] ; then
     LIST_OF_GROUPS="$*"; export LIST_OF_GROUPS
 elif [ "$LIST_OF_GROUPS" = "" ] ; then
-	echo "LIST_OF_GROUPS is empty in $ENVFILE"
-	exit 1
+    echo "LIST_OF_GROUPS is empty in $ENVFILE"
+    exit 1
 fi
 
-if [ ! -d $BASEDIR/logs ] ; then
-	mkdir $BASEDIR/logs
+if [ ! -d $LOGDIR ] ; then
+    mkdir $LOGDIR || (echo "Could not create log directory: $LOGDIR"; exit 1)
 fi
 
 for GROUP in $LIST_OF_GROUPS
@@ -129,5 +129,5 @@ END
 
 		echo
 		echo ending: `date`
-	) >$BASEDIR/logs/$GROUP.`date +%Y%m%d.%H%M%S` 2>&1 
+	) >$LOGDIR/$GROUP.`date +%Y%m%d.%H%M%S` 2>&1 
 done
