make svn fs-type configurable with --with-svn=fstype

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -700,6 +700,7 @@ MK_LCLSTATEDIR_FALSE
 CONF_INSTALL_TRUE
 CONF_INSTALL_FALSE
 RCSSYS
+SVN_FSTYPE
 MAILPLUS
 ADMINMAILPLUS
 DIRNAME
@@ -1316,10 +1317,15 @@ Optional Features:
                           install time (default: yes)
   --enable-conf-install   enable install of sample .conf files in sysconfdir
                           (default: yes)
-  --enable-svn            enable use of subversion instead of cvs
   --enable-mail-plus      enable mail to rancid+ addresses, instead of rancid-
   --enable-adminmail-plus enable mail to rancid-admin+ addresses, instead of
                           rancid-admin-
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-svn=fstype       use subversion instead of cvs, with optional svn
+                          fstype (fsfs|bdb)
 
 Some influential environment variables:
   CC          C compiler command
@@ -5835,25 +5841,48 @@ fi
 
 
 # Configure for subversion revision control system instead of CVS.
+SVN_FSTYPE="--fs-type fsfs"
 { echo "$as_me:$LINENO: checking whether subversion" >&5
 echo $ECHO_N "checking whether subversion... $ECHO_C" >&6; }
-# Check whether --enable-svn was given.
-if test "${enable_svn+set}" = set; then
-  enableval=$enable_svn; if test "$enable_svn" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
+
+# Check whether --with-svn was given.
+if test "${with_svn+set}" = set; then
+  withval=$with_svn;  case "$withval" in
+  yes)
+	{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-    RCSSYS="svn"
-else
-    { echo "$as_me:$LINENO: result: no" >&5
+	RCSSYS="svn"
+	;;
+  fsfs)
+	{ echo "$as_me:$LINENO: result: yes fstype fsfs" >&5
+echo "${ECHO_T}yes fstype fsfs" >&6; }
+	RCSSYS="svn"
+	SVN_FSTYPE="--fs-type fsfs"
+	;;
+  bdb)
+	{ echo "$as_me:$LINENO: result: yes fstype bdb" >&5
+echo "${ECHO_T}yes fstype bdb" >&6; }
+	RCSSYS="svn"
+	SVN_FSTYPE="--fs-type bdb"
+	;;
+  no)
+	{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-    RCSSYS="cvs"
-fi
+	RCSSYS="cvs"
+	;;
+  *)
+	{ { echo "$as_me:$LINENO: error: unknown svn fs-type $withval" >&5
+echo "$as_me: error: unknown svn fs-type $withval" >&2;}
+   { (exit 1); exit 1; }; }
+  esac
+
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
     RCSSYS="cvs"
 
 fi
+
 
 
 rd_cv_RCSSYS=$RCSSYS
@@ -7811,6 +7840,7 @@ MK_LCLSTATEDIR_FALSE!$MK_LCLSTATEDIR_FALSE$ac_delim
 CONF_INSTALL_TRUE!$CONF_INSTALL_TRUE$ac_delim
 CONF_INSTALL_FALSE!$CONF_INSTALL_FALSE$ac_delim
 RCSSYS!$RCSSYS$ac_delim
+SVN_FSTYPE!$SVN_FSTYPE$ac_delim
 MAILPLUS!$MAILPLUS$ac_delim
 ADMINMAILPLUS!$ADMINMAILPLUS$ac_delim
 DIRNAME!$DIRNAME$ac_delim
@@ -7821,7 +7851,6 @@ TAR!$TAR$ac_delim
 PERLV_PATH!$PERLV_PATH$ac_delim
 PERLV!$PERLV$ac_delim
 EXPECT_PATH!$EXPECT_PATH$ac_delim
-PING_PATH!$PING_PATH$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7863,6 +7892,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PING_PATH!$PING_PATH$ac_delim
 LG_PING_CMD!$LG_PING_CMD$ac_delim
 CVS!$CVS$ac_delim
 SVN!$SVN$ac_delim
@@ -7880,7 +7910,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 15; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
