add --{enable,disable}-conf-install to disabled installation of the sample .conf files into sysconfdir.  Like the previous commit, this makes packaging easier or better.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS VERSION PACKAGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP U ANSI2KNR MK_LCLSTATEDIR_TRUE MK_LCLSTATEDIR_FALSE MAILPLUS ADMINMAILPLUS DIRNAME DIFF DIFF_CMD SENDMAIL TAR PERLV_PATH PERLV EXPECT_PATH PING_PATH LG_PING_CMD CVS COMM FIND GREP ID MKDIR RSH SORT SSH TELNET TOUCH ENV_PATH LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS VERSION PACKAGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP U ANSI2KNR MK_LCLSTATEDIR_TRUE MK_LCLSTATEDIR_FALSE CONF_INSTALL_TRUE CONF_INSTALL_FALSE MAILPLUS ADMINMAILPLUS DIRNAME DIFF DIFF_CMD SENDMAIL TAR PERLV_PATH PERLV EXPECT_PATH PING_PATH LG_PING_CMD CVS COMM FIND GREP ID MKDIR RSH SORT SSH TELNET TOUCH ENV_PATH LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -851,6 +851,8 @@ Optional Features:
   --enable-mk-localstatedir
                           enable creation of the local state directory at
                           install time (default: yes)
+  --enable-conf-install   enable install of sample .conf files in sysconfdir
+                          (default: yes)
   --enable-mail-plus      enable mail to rancid+ addresses, instead of rancid-
   --enable-adminmail-plus enable mail to rancid-admin+ addresses, instead of
                           rancid-admin-
@@ -4959,7 +4961,6 @@ echo "${ECHO_T}yes" >&6
     enable_mk_localstatedir="yes"
 
 fi;
-#rd_cv_ADMINMAILPLUS=$ADMINMAILPLUS
 
 
 if test "${enable_mk_localstatedir}" = yes; then
@@ -4968,6 +4969,37 @@ if test "${enable_mk_localstatedir}" = yes; then
 else
   MK_LCLSTATEDIR_TRUE='#'
   MK_LCLSTATEDIR_FALSE=
+fi
+
+
+# Check if user wants us to create LOCALSTATEDIR.  If it's a package-system,
+# they might create it themselves for book-keeping sake; eg: NetBSD
+echo "$as_me:$LINENO: checking whether to install sample .conf files in sysconfdir" >&5
+echo $ECHO_N "checking whether to install sample .conf files in sysconfdir... $ECHO_C" >&6
+# Check whether --enable-conf-install or --disable-conf-install was given.
+if test "${enable_conf_install+set}" = set; then
+  enableval="$enable_conf_install"
+  if test "$enable_conf_install" = yes; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+else
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    enable_conf_install="yes"
+
+fi;
+
+
+if test "${enable_conf_install}" = yes; then
+  CONF_INSTALL_TRUE=
+  CONF_INSTALL_FALSE='#'
+else
+  CONF_INSTALL_TRUE='#'
+  CONF_INSTALL_FALSE=
 fi
 
 
@@ -6199,6 +6231,13 @@ echo "$as_me: error: conditional \"MK_LCLSTATEDIR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONF_INSTALL_TRUE}" && test -z "${CONF_INSTALL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONF_INSTALL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONF_INSTALL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -6818,6 +6857,8 @@ s,@U@,$U,;t t
 s,@ANSI2KNR@,$ANSI2KNR,;t t
 s,@MK_LCLSTATEDIR_TRUE@,$MK_LCLSTATEDIR_TRUE,;t t
 s,@MK_LCLSTATEDIR_FALSE@,$MK_LCLSTATEDIR_FALSE,;t t
+s,@CONF_INSTALL_TRUE@,$CONF_INSTALL_TRUE,;t t
+s,@CONF_INSTALL_FALSE@,$CONF_INSTALL_FALSE,;t t
 s,@MAILPLUS@,$MAILPLUS,;t t
 s,@ADMINMAILPLUS@,$ADMINMAILPLUS,;t t
 s,@DIRNAME@,$DIRNAME,;t t
