add par test for input file with a line per-cmd

diff --git a/tests/partest b/tests/partest
--- a/tests/partest
+++ b/tests/partest
@@ -54,7 +54,7 @@ if test $LN -ne 0; then
     exit 1
 fi
 
-echo "Testing command-line command on two input files (A + B) with -qnc"
+echo "Testing command-line command on two input files (A + B) with -qn1c"
 ../bin/par -q -n 1 -c 'echo -n {}' par.a.in par.b.in > par.ab.out
 svn diff par.ab.out >par.tmp
 if test $? -ne 0; then
@@ -67,9 +67,18 @@ if test $LN -ne 0; then
     exit 1
 fi
 
-# ( to indicate that the next one is a command)
-#clogin  -c "show users" hostname
-
+echo "Testing command-per-line on input file C with -qn1"
+../bin/par -q -n 1 par.c.in > par.c.out
+svn diff par.c.out >par.tmp
+if test $? -ne 0; then
+    echo "FAIL: svn diff par.c.out does not failed" >&2
+    exit 1
+fi
+LN=`wc -l par.tmp | sed -Ee 's/([0-9]+).*/\1/'`
+if test $LN -ne 0; then
+    echo "FAIL: par.c.out does not match expected output" >&2
+    exit 1
+fi
 
 rm -f par.tmp par.log.*
 echo PASS
