- merge acconfig.h into configure.in...finally.  this shuts-up autoconf, which   considers the external file method deprecated. - look for openpty() and pty.h - look for unsetenv & dont bother with bzero - define _GNU_SOURCE for linux

diff --git a/rancid/configure.in b/rancid/configure.in
--- a/rancid/configure.in
+++ b/rancid/configure.in
@@ -43,14 +43,23 @@ AC_C_STRINGIZE
 AC_HEADER_STDC
 AC_CHECK_HEADERS(limits.h memory.h siginfo.h string.h strings.h unistd.h)
 
-AC_CHECK_HEADERS(errno.h fcntl.h sys/types.h sys/wait.h)
+AC_CHECK_HEADERS(errno.h fcntl.h pty.h sys/types.h sys/wait.h)
 dnl AC_CHECK_HEADERS(errno.h stdlib.h sys/types.h sys/wait.h)
 dnl AC_CHECK_HEADERS(malloc.h)
 AC_CHECK_HEADERS(sysexits.h)
 
 # check functions
-AC_CHECK_FUNCS(memcpy memmove memset bcopy bzero strerror strchr strrchr \
-	strstr strtok strrtok index rindex)
+AC_CHECK_FUNCS(memcpy memmove memset strerror strchr \
+		strrchr strstr strtok strrtok index rindex unsetenv)
+AC_CHECK_FUNCS(openpty)
+if test $ac_cv_func_openlog+set != set; then
+  # openlog is not in the default libraries.  See if it is in some other lib.
+  for lib in util; do
+    AC_CHECK_LIB($lib, openpty, [AC_DEFINE(HAVE_OPENPTY)
+		 LIBS="$LIBS -l$lib"; break])
+  done
+fi
+
 dnl AC_FUNC_VPRINTF
 
 # type checks
@@ -299,7 +308,90 @@ AC_CONFIG_FILES(include/version.h)	# this is not a header in the sense of
 					# AC_CONFIG_HEADERS will cause
 					# autoheader to overwrite it, while all
 					# want is simple variable replacement
+# autoheader bits
+AH_TOP([
+#ifndef	CONFIG_H
+#define	CONFIG_H	1
+])
+AH_BOTTOM([
+
+/* damned linux... */
+#ifdef LINUX
+# define _GNU_SOURCE
+#endif
+
+#ifndef __P
+# if STDC_HEADERS
+#  define __P(a)	a
+# else
+#  define __P(a)	()
+# endif
+#endif
+
+#if HAVE_STDLIB_H
+# include <stdlib.h>
+#endif
+
+#if HAVE_UNISTD_H       
+# include <unistd.h>    
+# include <sys/types.h>
+#elif HAVE_SYS_TYPES_H 
+# include <sys/types.h>
+#endif  
+
+#if HAVE_ERRNO_H
+# include <errno.h>
+#endif
+extern int		errno;
+
+#if HAVE_STRING_H
+# include <string.h>    
+#endif
+#if HAVE_STRINGS_H      
+# include <strings.h>
+#endif 
+
+#if ! HAVE_STRERROR
+# define strerror(n)	sys_errlist[n];
+#endif
+
+#if HAVE_SYS_WAIT_H 
+# include <sys/wait.h>
+#endif  
+#ifndef WEXITSTATUS
+# define WEXITSTATUS(stat_val) ((unsigned)(stat_val) >> 8)
+#endif
+#ifndef WIFEXITED
+# define WIFEXITED(stat_val) (((stat_val) & 255) == 0)
+#endif  
+
+#if HAVE_MEMSET
+# define bzero(p,s)	memset(p, 0, s)
+# define bcopy(s,d,l)	memcpy(d, s, l)
+#endif
+
+#if HAVE_INDEX && ! HAVE_STRCHR
+# define index(s,c)	strchr(s,c)
+#endif
+
+#if HAVE_SYSEXITS_H
+# include <sysexits.h>
+#else
+					/* missing sysexits.h */
+# define EX_OK		0
+# define EX_USAGE	64		/* command line usage error */
+# define EX_NOINPUT	66		/* cannot open input */
+# define EX_TEMPFAIL	75		/* temp failure */
+# define EX_OSERR	71		/* system error */
+# define EX_CANTCREAT	73		/* can't create (user) output file */
+# define EX_IOERR	74		/* input/output error */
+# define EX_CONFIG	78		/* configuration error */
+#endif
+
+#endif	/* CONFIG_H */
+])
 AC_CONFIG_HEADERS(include/config.h)
+
 AC_CONFIG_FILES(bin/control_rancid bin/par bin/rancid-fe, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/alogin bin/arancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/blogin bin/brancid, [chmod a+x $ac_file])
