add ssh support and simple change for redback

diff --git a/rancid/bin/clogin.in b/rancid/bin/clogin.in
--- a/rancid/bin/clogin.in
+++ b/rancid/bin/clogin.in
@@ -29,8 +29,8 @@
 # Usage line
 set usage "Usage: $argv0 \[-u user\] \[-p user-password\] \[-v vty-password\] \
 \[-w enable-username\] \[-e enable-password\] \[-noenable\] \
-\[-f cloginrc-file\] \[-c command\] \[-s script-file\] \[-autoenable\] \
-\[-t timeout\] router \[router...\]\n"
+\[-f cloginrc-file\] \[-y ssh_cypher_type\] \[-c command\] \[-s script-file\] \
+\[-autoenable\] \[-t timeout\] router \[router...\]\n"
 
 # env(CLOGIN) may contain:
 #	x == do not set xterm banner or name
@@ -125,6 +125,13 @@ for {set i 0} {$i < $argc} {incr i} {
 		exit 1
 	    }
 	    set do_script 1
+       # cypher type
+        } -y* -
+        -Y* {
+            if {! [  regexp .\[eE\](.+) $arg ignore cypher]} {
+                incr i
+                set cypher [ lindex $argv $i ]
+            }
 	# alternate cloginrc file
 	} -f* -
 	-F* {
@@ -236,9 +243,10 @@ proc source_password_file { } {
 }
 
 # Log into the router.
-proc login { router user userpswd passwd enapasswd prompt } {
+proc login { router user userpswd passwd enapasswd prompt cyphertype } {
     global spawn_id in_proc do_command do_script
     set in_proc 1
+    set tryssh 1
 
     # Telnet to the router & try to login.
     if [ catch {spawn telnet $router} reason ] {
@@ -274,11 +282,23 @@ proc login { router user userpswd passwd enapasswd prompt } {
     # TACACS server is not working, then it will use the enable
     # passwd.  Or, the router might not have TACACS turned on,
     # then it will just send the passwd.
+    # if telnet fails with connection refused, try ssh
     expect {
-        eof { send_user "Error: Couldn't login\n"; wait; return 1 }
 	"Connection refused" { 
-	    expect eof
-	    send_user "Error: Connection Refused\n"; wait; return 1
+	    close; wait
+	    if { $tryssh } {
+            if [ catch {spawn ssh -c $cyphertype -x -l $user $router} reason ] {
+                send_user "Error: failed to ssh: $reason\n"
+                exit 1
+            }
+	    set tryssh 0
+            sleep 0.3
+	    exp_continue
+	    } else {
+                expect eof
+	        send_user "Error: Connection Refused\n"; wait; return 1
+	    }
+        } eof { send_user "Error: Couldn't login\n"; wait; return 1
 	} "Unknown host\r\n" { 
 	    expect eof
 	    send_user "Error: Unknown host\n"; wait; return 1
@@ -289,6 +309,14 @@ proc login { router user userpswd passwd enapasswd prompt } {
 	    expect eof
 	    send_user "Error: Unknown host\n"; wait; return 1
 	}
+	-re "Host key not found .* \(yes\/no\)\?"       {
+            send "yes\r"
+            send_user "Host $router added to the list of known hosts.\n"
+            exp_continue }
+        -re "HOST IDENTIFICATION HAS CHANGED.* \(yes\/no\)\?"   {
+            send "no\r"
+            send_user "Error: The host key for $router has changed.  update the known_hosts file accordingly.\n"
+            return 1 }
 	-re "(Username|login):"	{ send "$user\r"
 	    expect { 
 		eof             	{ send_user "Error: Couldn't login\n"; wait; return 1 }
@@ -297,7 +325,7 @@ proc login { router user userpswd passwd enapasswd prompt } {
 	    }
 	    exp_continue
 	}
-	"Password:"	{ send "$passwd\r"
+	"\[Pp]assword:"	{ send "$passwd\r"
 	    expect { 
 		eof             { send_user "Error: Couldn't login\n"; wait; return 1 }
 		"Password:"     { send "$enapasswd\r" }
@@ -360,7 +388,7 @@ proc run_commands { prompt command } {
 	    expect {
                 -re "^\[^\n\r]*$prompt."	{ exp_continue }
 		-re "^\[^\n\r *]*$prompt"	{}
-                "\n"				{ exp_continue }
+                -re "\[\n\r]"			{ exp_continue }
             }
 	}
     } else {
@@ -368,7 +396,7 @@ proc run_commands { prompt command } {
 	expect {
 		-re "^\[^\n\r]*$prompt."	{ exp_continue }
 		-re "^\[^\n\r *]*$prompt"	{}
-		"\n"				{ exp_continue }
+                -re "\[\n\r]"			{ exp_continue }
 	}
     }
     send "exit\r"
@@ -413,7 +441,7 @@ foreach router [lrange $argv $i end] {
         send_user "Error - no password for $router in $password_file.\n"
         continue
       } 
-      if { $do_enapasswd && !$autoenable && [llength $pswd] < 2 } {
+      if { $do_enapasswd && $autoenable == 0 && [llength $pswd] < 2 } {
 	send_user "Error - no enable password for $router in $password_file.\n"
         continue
       }
@@ -448,8 +476,17 @@ foreach router [lrange $argv $i end] {
       if { "$enauser" == "" } { set enauser $ruser } 
     } 
 
+    # Figure out cypher tpye
+    if {[info exists cypher]} {
+      # command line cypher type
+      set cyphertype $cypher
+    } else {
+      set cyphertype [find cyphertype $router]
+      if { "$cyphertype" == "" } { set cyphertype "3des" }
+    }
+
     # Login to the router
-    if {[login $router $ruser $userpswd $passwd $enapasswd $prompt]} {
+    if {[login $router $ruser $userpswd $passwd $enapasswd $prompt $cyphertype]} {
 	continue
     }
     if { $enable } { 
